### PR TITLE
Update TBS without projects for 0.2.0 

### PR DESCRIPTION
**Pull request by djoyahoy**
Issue #54

Please do not merge until we have 2 reviewers sign off.

### CODE REVIEW

**Comment by matthewmcnew** [comment]
This seems like useful information. I wonder if a world without `pb`  if this page should honestly be the opposite and on: "Using Tanzu Build Service With Projects" ?

**Comment by djoyahoy** [comment]
> This seems like useful information. I wonder if a world without `pb` if this page should honestly be the opposite and on: "Using Tanzu Build Service With Projects" ?

I was thinking that too. I'll make that change.

**Comment by djoyahoy** [comment]
Removing this page as it is no longer necessary.

**Comment by animatedmax** [comment]
Thank you @djoyahoy

**Pull request merged**
