### PR TITLE
Update installing-tap-profile.html.md.erb

### PR DESCRIPTION
**Pull request by mvalliath**

### CODE REVIEW

**Comment by RichardJJG** [comment]
We received your PR after the doc freeze date. We are currently working on release tasks, and we will review your PR as soon as we are able. Unfortunately, this may mean that your PR content will not be published until after the release. Going forward, to ensure that your PR changes are published on release day, please submit such PRs no later than 23:59 UTC-8 on the [doc freeze date](https://confluence.eng.vmware.com/pages/viewpage.action?pageId=789919969).

**Comment by mvalliath** [comment]
Hi @RichardJJG! 

Is this new policy? We've always updated the standalone TBS docs as we go. We try to get in our PRs to the `docs-tap` repo before docs freeze dates, but never assumed changes to the standalone TBS docs were subject to the docs freeze dates, because standalone TBS is separate product from TAP (it GA'd a couple years before TAP did).

**Comment by RichardJJG** [comment]
@snneji, can you speak to the above? I'm not aware of docs-build-service ever being exempt.

**Comment by RichardJJG** [comment]
@kcoriordan, can you speak to the above? I'm not aware of docs-build-service ever being exempt.

**Comment by RichardJJG** [comment]
Hi, @mvalliath, I was on Interrupt duty at the time and assumed docs-build-service was tied to the latest TAP patch releases (most smaller docs repos associated with the TAP core docs publish at exactly the same cadence, and it was safer than assuming otherwise at the time).

You're right that, if docs-build-service is not about to be published, then these docs are not frozen. I merged your PR within 2 hours of saying I might not be able to -- I was keen to set expectations =P

**Pull request merged**
