### PR TITLE
Update `Managing Secrets`

### PR DESCRIPTION
**Pull request by sukhil-suresh**
- resolves https://github.com/pivotal-cf/docs-build-service/issues/52

Signed-off-by: Sukhil Suresh <ssukhil@vmware.com>

### CODE REVIEW

**Comment by sukhil-suresh** [comment]
might be easier to review the new file (vs using diff)
- HackMD: https://hackmd.io/-7Y1i4nBTmy0J3K3xhxJlA?view
- erb file: https://github.com/pivotal-cf/docs-build-service/blob/ed7f47878a41e706989a9d67a7191ada80bd41dd/managing-secrets.html.md.erb

**Comment by tylerphelan** [comment]
@sukhil-suresh made some suggestions in a PR to this branch: https://github.com/pivotal-cf/docs-build-service/pull/74

**Comment by sukhil-suresh** [comment]
Chatted with @tylerphelan over the issues rasied in the the PR https://github.com/pivotal-cf/docs-build-service/pull/74

> secret -> credentials to not repeat "secret" twice

Adopting this, since it is more readable.

> remove reference to "projects" as I don't think we need it if we don't reference projects elsewhere

We came to the conclusion that if projects is still referred to in rest of the docs, we could hyperlink it to the projects related page. If projects is not mentioned elsewhere, drop the reference to `project` 

> Remove references to docker in the "registry secret" section incase it gets confused with a dockerhub registry secret

Would be nice to get others opinion on this. The assumption is that kpack/kp only supports Docker compliant registries? Or is it more correct to say any OCI conformant registry? Also, keeping in mind the secret is saved as a `kubernetes.io/dockerconfigjson` secret

> docker hub -> dockerhub

Agreed to stick with `Docker Hub` and `docker hub` as that seems to be the adopted format in Docker documentation.

**Comment by djoyahoy** [comment]
So i'd say: 
* create `docker hub` secrets with the `--dockerhub` flag
* create `gcr` secrets with the `--gcr` flag
* create artifactory, harbor, or ACR secrets with the `--registry` set of flags

**Comment by sukhil-suresh** [comment]
> if projects is still referred to in rest of the docs, we could hyperlink it to the projects related page

spotted a new file `tbs-with-projects.html.md.erb` as part of PR https://github.com/pivotal-cf/docs-build-service/pull/68
will link `project` reference to this page.

**Pull request merged**
